/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.Image;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import mundo.Aula;
import mundo.Estudiante;

/**
 *
 * @author jorge
 */
public class GUIPrincipal extends javax.swing.JFrame {

    Aula aula = new Aula();
    Estudiante estudiante;

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        initComponents();
        this.setTitle("Registro estudiantes");
        this.setResizable(false);
        this.setLocationRelativeTo(null);

        //Agregamos el button Group 
        btGGenero.add(rbMasculino);
        btGGenero.add(rbFemenino);

        //Inicializando primer estudiante.
        estudiante = aula.getEstudianteBase();
        txtCodigo.setText(estudiante.getCodigo());
        txtNombre.setText(estudiante.getNombre());

        if (estudiante.getGenero() == "M") {
            rbMasculino.setSelected(true);
        } else {
            rbFemenino.setSelected(true);
        }

        txtPrograma.setText(estudiante.getPrograma());

        jcbSemestre.setSelectedIndex(estudiante.getSemestre() - 1);

        txtPromedio.setText(estudiante.getPromedio() + "");

        ImageIcon blaine = new ImageIcon(estudiante.getImagen());

        Icon icon = new ImageIcon(blaine.getImage().getScaledInstance(lblFotos.getWidth(), lblFotos.getHeight(), Image.SCALE_DEFAULT));

        lblFotos.setIcon(icon);

        this.repaint();

    }

    //estudiantes.add(new Estudiante("19458345", "David Blaine", "M", "Diseño Grafico",6, 4.5,"src//"));
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btGGenero = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rbMasculino = new javax.swing.JRadioButton();
        rbFemenino = new javax.swing.JRadioButton();
        txtPrograma = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jcbSemestre = new javax.swing.JComboBox<>();
        btnSiguiente = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtPromedio = new javax.swing.JTextField();
        btnInfo = new javax.swing.JButton();
        lblFotos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Codigo");

        txtCodigo.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Nombre");

        txtNombre.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Genero");

        rbMasculino.setText("M");

        rbFemenino.setText("F");

        txtPrograma.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Programa");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Semestre");

        jcbSemestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        btnSiguiente.setText(">");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnAnterior.setText("<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Promedio");

        txtPromedio.setEditable(false);

        btnInfo.setText("Inf.");
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        lblFotos.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addGap(12, 12, 12))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)))
                            .addComponent(jLabel1))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbMasculino)
                                .addGap(44, 44, 44)
                                .addComponent(rbFemenino))
                            .addComponent(jcbSemestre, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPrograma, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigo)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnAnterior)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnSiguiente)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnInfo))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(33, 33, 33)
                            .addComponent(txtPromedio)
                            .addGap(2, 2, 2))))
                .addGap(18, 18, 18)
                .addComponent(lblFotos, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbFemenino)
                            .addComponent(rbMasculino)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jcbSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAnterior)
                            .addComponent(btnSiguiente)
                            .addComponent(btnBuscar)
                            .addComponent(btnInfo)))
                    .addComponent(lblFotos, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // TODO add your handling code here:
        if (aula.getPosicion() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Llego al inicio de la lista", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        } else {
            estudiante = aula.getAnteriorEstudiante();
            //Agregamos el button Group 
            btGGenero.add(rbMasculino);
            btGGenero.add(rbFemenino);

            //Inicializando primer estudiante.
            estudiante = aula.getEstudianteBase();
            txtCodigo.setText(estudiante.getCodigo());
            txtNombre.setText(estudiante.getNombre());

            if (estudiante.getGenero() == "M") {
                rbMasculino.setSelected(true);
            } else {
                rbFemenino.setSelected(true);
            }

            txtPrograma.setText(estudiante.getPrograma());

            jcbSemestre.setSelectedIndex(estudiante.getSemestre() - 1);

            txtPromedio.setText(estudiante.getPromedio() + "");

            ImageIcon blaine = new ImageIcon(estudiante.getImagen());

            Icon icon = new ImageIcon(blaine.getImage().getScaledInstance(lblFotos.getWidth(), lblFotos.getHeight(), Image.SCALE_DEFAULT));

            lblFotos.setIcon(icon);

            this.repaint();
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Desarrollado por -Nombre-", "Informacion", HEIGHT);
    }//GEN-LAST:event_btnInfoActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:

        if (aula.getPosicion() == 9) {
            JOptionPane.showMessageDialog(rootPane, "Llego al final de la lista", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        } else {

            estudiante = aula.getSiguienteEstudiante();

            //Agregamos el button Group 
            btGGenero.add(rbMasculino);
            btGGenero.add(rbFemenino);

            txtCodigo.setText(estudiante.getCodigo());
            txtNombre.setText(estudiante.getNombre());

            if (estudiante.getGenero() == "M") {
                rbMasculino.setSelected(true);
            } else {
                rbFemenino.setSelected(true);
            }

            txtPrograma.setText(estudiante.getPrograma());

            jcbSemestre.setSelectedIndex(estudiante.getSemestre() - 1);

            txtPromedio.setText(estudiante.getPromedio() + "");

            ImageIcon blaine = new ImageIcon(estudiante.getImagen());

            Icon icon = new ImageIcon(blaine.getImage().getScaledInstance(lblFotos.getWidth(), lblFotos.getHeight(), Image.SCALE_DEFAULT));

            lblFotos.setIcon(icon);

            this.repaint();
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String codigo = JOptionPane.showInputDialog(rootPane, "Ingrese el codigo del estudiante", "Buscar", JOptionPane.INFORMATION_MESSAGE);
        boolean encontrado = false;
        
        for (int i = 0; i < 10; i++) {

            if (aula.getEstudiantes().get(i).getCodigo().equals(codigo)) {

                Estudiante estudiante = aula.getEstudiantes().get(i);

                btGGenero.add(rbMasculino);
                btGGenero.add(rbFemenino);

                txtCodigo.setText(estudiante.getCodigo());
                txtNombre.setText(estudiante.getNombre());

                if (estudiante.getGenero() == "M") {
                    rbMasculino.setSelected(true);
                } else {
                    rbFemenino.setSelected(true);
                }

                txtPrograma.setText(estudiante.getPrograma());

                jcbSemestre.setSelectedIndex(estudiante.getSemestre() - 1);

                txtPromedio.setText(estudiante.getPromedio() + "");

                ImageIcon blaine = new ImageIcon(estudiante.getImagen());

                Icon icon = new ImageIcon(blaine.getImage().getScaledInstance(lblFotos.getWidth(), lblFotos.getHeight(), Image.SCALE_DEFAULT));

                lblFotos.setIcon(icon);

                this.repaint();

                JOptionPane.showMessageDialog(rootPane, "Estudiante encontrado!", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                
                encontrado = true;
                
                break;

            }

        }
        
        if(encontrado == false){
                JOptionPane.showMessageDialog(rootPane, "Estudiante no encontrado", "Informaicion", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btGGenero;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> jcbSemestre;
    private javax.swing.JLabel lblFotos;
    private javax.swing.JRadioButton rbFemenino;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrograma;
    private javax.swing.JTextField txtPromedio;
    // End of variables declaration//GEN-END:variables
}
